
services:
    hub:
        image: selenium/hub:latest
        ports: 
          - 4444:4444
    chrome:
        image: selenium/node-chrome-debug:latest
        environment:
          - HUB_PORT_4444_TCP_ADDR=hub
          - HUB_PORT_4444_TCP_PORT=4444
        ports:
          - 5900:5900
        depends_on:
          - hub
